name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create Repo Name
      run: |
        echo "REPO_NAME=${REGISTRY}/${IMAGE_NAME,,}" >>${GITHUB_ENV}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REPO_NAME }}
        tags: |
          type=ref,event=branch
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: og in to ${{ env.REGISTRY }} container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./server
        file: Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.REPO_NAME }}:latest
        push: true